### ISSUE TITLE
missing file wikt.mw

### ISSUE THREAD

**Issue by drumilT** [kbatsuren/wiktra#1]
lupa._lupa.LuaError: [string "<python>"]:1: module 'wikt.mw' not found:
is raised when trying to import translite

**Comment by kbatsuren** [comment]
I am sorry for the terribly late reply. I will look into this issue as soon as possible.

**Comment by kbatsuren** [comment]
I suppose the pull request fixes this issue? :)

**Comment by drumilT** [comment]
Hi, thanks for the reply, no the pull request wont fix this

**Comment by kbatsuren** [comment]
The file is actually not missing, but I must agree that I tested only the code from the command line, and it worked. This issue raises in all other environments—e.g., in the python notebook. This issue happens due to the Lua environment path parameters (Simply the tool couldn't locate where the file is). I will fix it asap.

**Comment by kbatsuren** [comment]
Please let me know if it solves your problem.

In Windows you can see similar error: 
![image](https://user-images.githubusercontent.com/50955407/111557773-4671bc80-87c8-11eb-909d-bbb028b8b4a4.png)

Here all you need to do is two things. 
  1) create a folder 'lua' in 'C:\ProgramData\Miniconda3\'
  2) copy the entire folder of wikt from this project and paste it into 'C:\ProgramData\Miniconda3\lua'

If you are using Linux or macOS, please send me the full lines of the error.
Usually, the main directory is '/usr/local', and here you can create a folder 'lua/5.3/'. And the second step is the same.

I do apologize that it is an ugly fix. I will fix it properly but it takes time.

**Comment by kbatsuren** [comment]
@aryamccarthy Hi Arya,

Please let me know if you can use WikTra with this solution.
